on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest, 'macos-latest']

    steps:
        -   name: Check out repository
            uses: actions/checkout@v4
        -   name: Set up python
            id: setup-python
            uses: actions/setup-python@v5
            with:
                python-version: 3.11

        - run: pip install -r requirements.txt pyinstaller
        - run: pyinstaller src/hello.py
        
        - run: ./dist/hello/hello
        -   uses: actions/upload-artifact@v2
            with:
                path: dist/*