name: executable-using-python-requirements-new

on:
   push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller src/hello.py

      - name: Running the executable
        run: ./dist/hello/hello

      - name: Upload the executable
        id: upload-executable
        uses: actions/upload-artifact@v4
        with:
          name: hello-${{matrix.os}}
          path: dist/hello/*
      - name: print atrifact details
        run: |
          echo ${{steps.upload-executable.outputs.artifact-url}}
          echo ${{steps.upload-executable.outputs.artifact-id}}

  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
    needs: build

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: hello-${{ matrix.os }}
          
      - name: Display structure of downloaded files
        run: ls -R

      - name: Create github release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          draft: true
          prerelease: true
          artifacts: hello-${{ matrix.os }}
